[package]
name = "react-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.93"
web-sys = { version = "0.3.55", features = ["Document", "Element", "Window", "console"] }
